"""
Accessibility audit HTML report generator.

Generates a self-contained, interactive HTML page with:
- Engine summary cards with violation counts and impact breakdown
- WCAG Success Criterion pivot table (sortable, filterable)
- Disagreements and disparities tables (multi-engine)
- Per-engine rule detail tabs with expandable node info
- Recommendations section
- Light/dark theme with system preference detection
- Accessible: skip links, semantic HTML, ARIA tabs, keyboard nav
"""

from __future__ import annotations

import html as html_mod


def generate_a11y_report_html(data: dict) -> str:
    """Generate a complete self-contained HTML report from enriched audit data.

    Args:
        data: Enriched report data dict from _build_enriched_report_data()

    Returns:
        Complete HTML document as a string
    """
    url = _esc(data.get("url", ""))
    timestamp = _esc(data.get("timestamp", ""))
    level = _esc(data.get("level", ""))
    engine_list = data.get("execution_order", [])
    is_multi = len(engine_list) > 1

    sections = [
        _render_summary(data),
        _render_wcag_table(data),
    ]

    if is_multi:
        sections.append(_render_disagreements(data))
        sections.append(_render_disparities(data))

    sections.append(_render_engine_details(data))

    if data.get("recommendations"):
        sections.append(_render_recommendations(data))

    main_content = "\n".join(sections)

    nav_links = [
        ("summary", "Summary"),
        ("wcag-table", "WCAG Criteria"),
    ]
    if is_multi:
        nav_links.append(("disagreements", "Disagreements"))
        nav_links.append(("disparities", "Disparities"))
    nav_links.append(("engine-details", "Engine Details"))
    if data.get("recommendations"):
        nav_links.append(("recommendations", "Recommendations"))

    nav_items = "\n".join(f'        <a href="#{id_}">{label}</a>' for id_, label in nav_links)

    level_display = _format_level(level)

    return f'''<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Accessibility Audit Report — {url}</title>
    <style>
{_get_report_css()}
    </style>
</head>
<body>
    <a href="#main-content" class="skip-link">Skip to main content</a>

    <header class="report-header">
        <div class="header-content">
            <div class="header-text">
                <h1>Accessibility Audit Report</h1>
                <p class="header-meta">
                    <a href="{url}" target="_blank" rel="noopener">{url}</a>
                    <span class="separator" aria-hidden="true">|</span>
                    <span>WCAG {level_display}</span>
                    <span class="separator" aria-hidden="true">|</span>
                    <time datetime="{timestamp}">{timestamp}</time>
                </p>
            </div>
            <button class="theme-toggle" id="theme-toggle" type="button" aria-label="Toggle dark/light mode">
                <span class="icon-sun" aria-hidden="true">&#9728;&#65039;</span>
                <span class="icon-moon" aria-hidden="true">&#9790;&#65039;</span>
            </button>
        </div>
    </header>

    <nav class="report-nav" aria-label="Report sections">
{nav_items}
    </nav>

    <main id="main-content">
{main_content}
    </main>

    <footer class="report-footer">
        <p>Generated by <strong>Inspekt</strong> at {timestamp}</p>
    </footer>

    <script>
{_get_report_js()}
    </script>
</body>
</html>'''


def _esc(text: str) -> str:
    """Escape HTML special characters."""
    return html_mod.escape(str(text)) if text else ""


def _format_level(level: str) -> str:
    """Format level code to display string (e.g. '21aa' -> '2.1 AA')."""
    level = level.lower()
    if level.startswith("22"):
        return f"2.2 {level[2:].upper()}"
    elif level.startswith("21"):
        return f"2.1 {level[2:].upper()}"
    elif level.startswith("2"):
        return f"2.0 {level[1:].upper()}"
    return level.upper()


def _impact_class(impact: str) -> str:
    """Return CSS class for impact level."""
    return (
        f"impact-{impact}"
        if impact in ("critical", "serious", "moderate", "minor")
        else "impact-unknown"
    )


def _status_class(status: str) -> str:
    """Return CSS class for status."""
    if status == "pass":
        return "status-pass"
    elif status in ("violation", "potentialviolation"):
        return "status-violation"
    elif status in ("incomplete",):
        return "status-incomplete"
    return "status-unknown"


def _render_summary(data: dict) -> str:
    """Render the summary section with engine cards and agreement gauge."""
    engines = data.get("engines", {})
    engine_list = data.get("execution_order", [])
    analysis = data.get("analysis", {})
    is_multi = len(engine_list) > 1

    cards = []
    for eng in engine_list:
        info = engines.get(eng, {})
        name = _esc(info.get("name", eng))
        abbr = _esc(info.get("abbr", eng.upper()))
        version = _esc(info.get("version", "?"))
        violations = info.get("violations", 0)
        passes = info.get("passes", 0)
        incomplete = info.get("incomplete", 0)
        error = info.get("error")

        if error:
            cards.append(f'''
        <div class="engine-card engine-card-error" data-engine="{_esc(eng)}">
            <div class="card-header">
                <span class="engine-name">{name}</span>
                <span class="engine-abbr">{abbr}</span>
            </div>
            <div class="card-body">
                <span class="error-msg">Error: {_esc(str(error))}</span>
            </div>
        </div>''')
            continue

        impact_html = ""
        impact_summary = info.get("impact_summary")
        if impact_summary:
            parts = []
            for level_name in ("critical", "serious", "moderate", "minor"):
                count = impact_summary.get(level_name, 0)
                if count > 0:
                    parts.append(
                        f'<span class="impact-badge {_impact_class(level_name)}">{count} {level_name}</span>'
                    )
            if parts:
                impact_html = f'<div class="impact-breakdown">{"".join(parts)}</div>'

        cards.append(f'''
        <div class="engine-card" data-engine="{_esc(eng)}">
            <div class="card-header">
                <span class="engine-name">{name}</span>
                <span class="engine-version">v{version}</span>
            </div>
            <div class="card-body">
                <div class="violation-count">{violations}</div>
                <div class="violation-label">{"violation" if violations == 1 else "violations"}</div>
                <div class="card-stats">
                    <span class="stat-pass">{passes} passed</span>
                    <span class="stat-incomplete">{incomplete} incomplete</span>
                </div>
                {impact_html}
            </div>
        </div>''')

    cards_html = "\n".join(cards)

    agreement_html = ""
    if is_multi:
        pct = analysis.get("agreement_percentage", 0)
        total = analysis.get("total_criteria_evaluated", 0)
        full = analysis.get("full_agreement_count", 0)
        issues = analysis.get("total_criteria_with_issues", 0)

        gauge_class = "gauge-high" if pct >= 90 else ("gauge-medium" if pct >= 70 else "gauge-low")

        agreement_html = f"""
        <div class="agreement-section">
            <h3>Engine Agreement</h3>
            <div class="agreement-gauge {gauge_class}">
                <div class="gauge-bar" style="width: {pct}%"></div>
                <span class="gauge-label">{pct}%</span>
            </div>
            <p class="agreement-detail">{full} of {total} criteria with full agreement &middot; {issues} criteria with issues</p>
        </div>"""

    return f"""
    <section id="summary" aria-labelledby="summary-heading">
        <h2 id="summary-heading">Summary</h2>
        <div class="engine-cards">
{cards_html}
        </div>
{agreement_html}
    </section>"""


def _render_wcag_table(data: dict) -> str:
    """Render the WCAG Success Criterion pivot table."""
    consolidated = data.get("consolidated", {})
    engine_list = data.get("execution_order", [])
    engines = data.get("engines", {})

    if not consolidated:
        return """
    <section id="wcag-table" aria-labelledby="wcag-heading">
        <h2 id="wcag-heading">WCAG Criteria</h2>
        <p>No criteria to display.</p>
    </section>"""

    # Sort SCs
    def sc_sort_key(sc):
        parts = sc.split(".")
        return tuple(int(p) for p in parts)

    sorted_scs = sorted(consolidated.keys(), key=sc_sort_key)

    # Build header
    engine_headers = ""
    for eng in engine_list:
        abbr = _esc(engines.get(eng, {}).get("abbr", eng.upper()))
        engine_headers += f"<th data-sortable>{abbr}</th>"

    # Build rows
    rows = []
    has_passes = False
    for sc in sorted_scs:
        entry = consolidated[sc]
        desc = _esc(entry.get("description", ""))
        conf_level = _esc(entry.get("conformance_level", ""))

        # Determine if this SC has any issues
        has_issue = False
        cells = []
        for eng in engine_list:
            status = entry.get(f"{eng}_status", "pass")
            count = entry.get(f"{eng}_count", 0)
            impact = entry.get(f"{eng}_impact", "")

            if status != "pass":
                has_issue = True
                label = f"{count}" if count else status
                title = f"{impact}: {count} issue(s)" if impact else f"{count} issue(s)"
                cells.append(
                    f'<td class="{_status_class(status)}" title="{_esc(title)}" data-sort-value="{count}">{label}</td>'
                )
            else:
                cells.append('<td class="status-pass" data-sort-value="0">Pass</td>')

        if not has_issue:
            has_passes = True

        row_class = "row-pass" if not has_issue else ""
        cells_html = "".join(cells)
        rows.append(
            f'<tr class="{row_class}" data-has-issue="{str(has_issue).lower()}">'
            f'<td class="sc-number">{_esc(sc)}</td>'
            f'<td class="sc-level">{conf_level}</td>'
            f'<td class="sc-desc">{desc}</td>'
            f"{cells_html}</tr>"
        )

    rows_html = "\n            ".join(rows)

    filter_html = ""
    if has_passes:
        filter_html = """
        <div class="table-controls">
            <label class="filter-toggle">
                <input type="checkbox" id="filter-passes" checked>
                <span>Hide passing criteria</span>
            </label>
        </div>"""

    return f"""
    <section id="wcag-table" aria-labelledby="wcag-heading">
        <h2 id="wcag-heading">WCAG Criteria</h2>
{filter_html}
        <div class="table-scroll">
            <table class="data-table sortable-table" id="wcag-data-table">
                <thead>
                    <tr>
                        <th data-sortable>SC</th>
                        <th data-sortable>Level</th>
                        <th data-sortable>Description</th>
                        {engine_headers}
                    </tr>
                </thead>
                <tbody>
            {rows_html}
                </tbody>
            </table>
        </div>
    </section>"""


def _render_disagreements(data: dict) -> str:
    """Render the disagreements section."""
    analysis = data.get("analysis", {})
    disagreements = analysis.get("disagreements", [])

    if not disagreements:
        return """
    <section id="disagreements" aria-labelledby="disagreements-heading">
        <h2 id="disagreements-heading">Disagreements</h2>
        <p class="empty-state">No disagreements — all engines agree on every criterion.</p>
    </section>"""

    rows = []
    for item in disagreements:
        sc = _esc(item.get("sc", ""))
        desc = _esc(item.get("description", ""))
        conf_level = _esc(item.get("conformance_level", ""))

        failing = ", ".join(
            f"{_esc(e['abbr'])} ({e['count']})" for e in item.get("failing_engines", [])
        )
        passing = ", ".join(_esc(e["abbr"]) for e in item.get("passing_engines", []))

        rows.append(
            f'<tr><td class="sc-number">{sc}</td><td>{conf_level}</td>'
            f"<td>{desc}</td>"
            f'<td class="text-fail">{failing}</td>'
            f'<td class="text-pass">{passing}</td></tr>'
        )

    rows_html = "\n            ".join(rows)

    return f"""
    <section id="disagreements" aria-labelledby="disagreements-heading">
        <h2 id="disagreements-heading">Disagreements</h2>
        <p class="section-desc">Criteria where some engines find issues and others pass.</p>
        <div class="table-scroll">
            <table class="data-table">
                <thead>
                    <tr>
                        <th>SC</th>
                        <th>Level</th>
                        <th>Description</th>
                        <th>Failing Engines</th>
                        <th>Passing Engines</th>
                    </tr>
                </thead>
                <tbody>
            {rows_html}
                </tbody>
            </table>
        </div>
    </section>"""


def _render_disparities(data: dict) -> str:
    """Render the disparities section."""
    analysis = data.get("analysis", {})
    disparities = analysis.get("disparities", [])
    engine_list = data.get("execution_order", [])
    engines = data.get("engines", {})

    if not disparities:
        return """
    <section id="disparities" aria-labelledby="disparities-heading">
        <h2 id="disparities-heading">Disparities</h2>
        <p class="empty-state">No significant count disparities between engines.</p>
    </section>"""

    rows = []
    for item in disparities:
        sc = _esc(item.get("sc", ""))
        desc = _esc(item.get("description", ""))
        conf_level = _esc(item.get("conformance_level", ""))
        counts = item.get("counts", {})
        ratio = item.get("ratio", 0)

        count_parts = []
        for eng in engine_list:
            abbr = _esc(engines.get(eng, {}).get("abbr", eng.upper()))
            c = counts.get(eng, 0)
            count_parts.append(f"{abbr}: {c}")
        counts_str = " vs ".join(count_parts)

        rows.append(
            f'<tr><td class="sc-number">{sc}</td><td>{conf_level}</td>'
            f"<td>{desc}</td>"
            f"<td>{_esc(counts_str)}</td>"
            f"<td>{ratio}x</td></tr>"
        )

    rows_html = "\n            ".join(rows)

    return f"""
    <section id="disparities" aria-labelledby="disparities-heading">
        <h2 id="disparities-heading">Disparities</h2>
        <p class="section-desc">Criteria where all engines find issues but counts differ by 2x or more.</p>
        <div class="table-scroll">
            <table class="data-table">
                <thead>
                    <tr>
                        <th>SC</th>
                        <th>Level</th>
                        <th>Description</th>
                        <th>Counts</th>
                        <th>Ratio</th>
                    </tr>
                </thead>
                <tbody>
            {rows_html}
                </tbody>
            </table>
        </div>
    </section>"""


def _render_engine_details(data: dict) -> str:
    """Render per-engine rule detail tabs."""
    engine_details = data.get("engine_details", {})
    engine_list = data.get("execution_order", [])
    engines = data.get("engines", {})

    if not engine_details:
        return ""

    # Build tabs
    tabs = []
    panels = []

    for idx, eng in enumerate(engine_list):
        detail = engine_details.get(eng, {})
        info = engines.get(eng, {})
        name = _esc(info.get("name", eng))
        abbr = _esc(info.get("abbr", eng.upper()))
        is_first = idx == 0

        # Error state
        if isinstance(detail, dict) and detail.get("error"):
            tab_id = f"tab-{_esc(eng)}"
            panel_id = f"panel-{_esc(eng)}"
            selected = "true" if is_first else "false"
            tabindex = "0" if is_first else "-1"
            hidden = "" if is_first else " hidden"
            active = " active" if is_first else ""

            tabs.append(
                f'<button role="tab" id="{tab_id}" aria-selected="{selected}" '
                f'aria-controls="{panel_id}" tabindex="{tabindex}" class="tab{active}">'
                f"{name} ({abbr})</button>"
            )
            panels.append(
                f'<div role="tabpanel" id="{panel_id}" aria-labelledby="{tab_id}" '
                f'class="tab-panel"{hidden}>'
                f'<p class="error-msg">Error: {_esc(str(detail["error"]))}</p></div>'
            )
            continue

        violations = detail.get("violations", [])
        v_count = len(violations)
        tab_label = f"{name} ({v_count})"

        tab_id = f"tab-{_esc(eng)}"
        panel_id = f"panel-{_esc(eng)}"
        selected = "true" if is_first else "false"
        tabindex = "0" if is_first else "-1"
        hidden = "" if is_first else " hidden"
        active = " active" if is_first else ""

        tabs.append(
            f'<button role="tab" id="{tab_id}" aria-selected="{selected}" '
            f'aria-controls="{panel_id}" tabindex="{tabindex}" class="tab{active}">'
            f"{_esc(tab_label)}</button>"
        )

        # Build panel content
        if not violations:
            panel_content = '<p class="empty-state">No violations found by this engine.</p>'
        else:
            rule_rows = []
            for v in violations:
                rule_id = _esc(v.get("rule_id", ""))
                impact = _esc(v.get("impact", ""))
                count = v.get("count", 0)
                desc = _esc(v.get("description", ""))
                help_url = v.get("help_url", "")
                nodes = v.get("nodes", [])

                rule_link = (
                    f'<a href="{_esc(help_url)}" target="_blank" rel="noopener">{rule_id}</a>'
                    if help_url
                    else rule_id
                )

                # Node details (expandable)
                nodes_html = ""
                if nodes:
                    node_items = []
                    for node in nodes:
                        selector = _esc(node.get("selector", ""))
                        node_html = _esc(node.get("html", ""))
                        failure = _esc(node.get("failure_summary", ""))

                        node_parts = []
                        if selector:
                            node_parts.append(
                                f'<div class="node-selector"><code>{selector}</code></div>'
                            )
                        if node_html:
                            node_parts.append(
                                f'<div class="node-html"><pre><code>{node_html}</code></pre></div>'
                            )
                        if failure:
                            node_parts.append(f'<div class="node-failure">{failure}</div>')

                        node_items.append(f'<li class="node-item">{"".join(node_parts)}</li>')

                    nodes_list = "\n".join(node_items)
                    nodes_html = f"""
                        <details class="node-details">
                            <summary>{len(nodes)} affected element{"s" if len(nodes) != 1 else ""}</summary>
                            <ul class="node-list">{nodes_list}</ul>
                        </details>"""

                rule_rows.append(
                    f"<tr>"
                    f'<td class="rule-id">{rule_link}</td>'
                    f'<td><span class="impact-badge {_impact_class(impact)}">{impact}</span></td>'
                    f'<td class="count-cell">{count}</td>'
                    f"<td>{desc}{nodes_html}</td>"
                    f"</tr>"
                )

            rules_html = "\n".join(rule_rows)
            panel_content = f"""
                <div class="table-scroll">
                    <table class="data-table rule-table">
                        <thead>
                            <tr>
                                <th>Rule</th>
                                <th>Impact</th>
                                <th>Count</th>
                                <th>Description</th>
                            </tr>
                        </thead>
                        <tbody>
                    {rules_html}
                        </tbody>
                    </table>
                </div>"""

        panels.append(
            f'<div role="tabpanel" id="{panel_id}" aria-labelledby="{tab_id}" '
            f'class="tab-panel"{hidden}>{panel_content}</div>'
        )

    tabs_html = "\n        ".join(tabs)
    panels_html = "\n    ".join(panels)

    return f"""
    <section id="engine-details" aria-labelledby="engine-details-heading">
        <h2 id="engine-details-heading">Engine Details</h2>
        <div class="tabs-container">
            <div class="tabs" role="tablist" aria-label="Engine detail tabs">
        {tabs_html}
            </div>
    {panels_html}
        </div>
    </section>"""


def _render_recommendations(data: dict) -> str:
    """Render the recommendations section."""
    recs = data.get("recommendations", {})
    if not recs or recs.get("total", 0) == 0:
        return ""

    by_sc = recs.get("by_sc", {})

    groups = []
    for sc in sorted(by_sc.keys()):
        items = by_sc[sc]
        sc_display = _esc(sc) if sc != "unknown" else "General"

        item_rows = []
        for item in items:
            engine = _esc(item.get("engine", ""))
            rule_id = _esc(item.get("rule_id", ""))
            level = _esc(item.get("level", ""))
            message = _esc(item.get("message", ""))

            item_rows.append(
                f'<tr><td>{engine}</td><td class="rule-id">{rule_id}</td>'
                f"<td>{level}</td><td>{message}</td></tr>"
            )

        items_html = "\n".join(item_rows)
        groups.append(f"""
            <details class="rec-group">
                <summary>SC {sc_display} ({len(items)} item{"s" if len(items) != 1 else ""})</summary>
                <table class="data-table rec-table">
                    <thead>
                        <tr><th>Engine</th><th>Rule</th><th>Level</th><th>Message</th></tr>
                    </thead>
                    <tbody>{items_html}</tbody>
                </table>
            </details>""")

    groups_html = "\n".join(groups)

    return f"""
    <section id="recommendations" aria-labelledby="recommendations-heading">
        <h2 id="recommendations-heading">Recommendations</h2>
        <p class="section-desc">{recs.get("total", 0)} items requiring manual review or consideration.</p>
{groups_html}
    </section>"""


def _get_report_css() -> str:
    """Return the complete CSS for the report."""
    return """
/* ===== Reset & Variables ===== */
*, *::before, *::after { box-sizing: border-box; }

:root {
    color-scheme: light dark;
    --bg-primary: #ffffff;
    --bg-secondary: #f6f8fa;
    --bg-code: #f0f3f6;
    --text-primary: #1f2328;
    --text-secondary: #656d76;
    --border-color: #d0d7de;
    --accent: #0969da;
    --accent-hover: #0550ae;
    --success: #1a7f37;
    --success-bg: #dafbe1;
    --warning: #9a6700;
    --warning-bg: #fff8c5;
    --error: #cf222e;
    --error-bg: #ffebe9;
    --shadow: 0 1px 3px rgba(0,0,0,0.08);
    --radius: 8px;
    --radius-sm: 4px;
    --font-mono: ui-monospace, SFMono-Regular, "SF Mono", Menlo, monospace;
    --font-sans: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
}

[data-theme="dark"] {
    --bg-primary: #0d1117;
    --bg-secondary: #161b22;
    --bg-code: #1c2128;
    --text-primary: #e6edf3;
    --text-secondary: #8b949e;
    --border-color: #30363d;
    --accent: #58a6ff;
    --accent-hover: #79c0ff;
    --success: #3fb950;
    --success-bg: #0d2818;
    --warning: #d29922;
    --warning-bg: #2d1f00;
    --error: #f85149;
    --error-bg: #3d1214;
    --shadow: 0 1px 3px rgba(0,0,0,0.3);
}

@media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) {
        --bg-primary: #0d1117;
        --bg-secondary: #161b22;
        --bg-code: #1c2128;
        --text-primary: #e6edf3;
        --text-secondary: #8b949e;
        --border-color: #30363d;
        --accent: #58a6ff;
        --accent-hover: #79c0ff;
        --success: #3fb950;
        --success-bg: #0d2818;
        --warning: #d29922;
        --warning-bg: #2d1f00;
        --error: #f85149;
        --error-bg: #3d1214;
        --shadow: 0 1px 3px rgba(0,0,0,0.3);
    }
}

/* ===== Base ===== */
body {
    font-family: var(--font-sans);
    background: var(--bg-primary);
    color: var(--text-primary);
    line-height: 1.6;
    margin: 0;
    padding: 0;
}

a { color: var(--accent); text-decoration: none; }
a:hover { text-decoration: underline; }

code {
    font-family: var(--font-mono);
    font-size: 0.875em;
    background: var(--bg-code);
    padding: 2px 6px;
    border-radius: var(--radius-sm);
}

pre code {
    display: block;
    padding: 8px 12px;
    overflow-x: auto;
    white-space: pre-wrap;
    word-break: break-word;
}

/* ===== Skip Link ===== */
.skip-link {
    position: absolute;
    top: -100%;
    left: 16px;
    padding: 8px 16px;
    background: var(--accent);
    color: #fff;
    border-radius: var(--radius-sm);
    z-index: 1000;
    transition: top 0.2s;
}
.skip-link:focus {
    top: 8px;
}

/* ===== Header ===== */
.report-header {
    background: var(--bg-secondary);
    border-bottom: 1px solid var(--border-color);
    padding: 24px 32px;
}
.header-content {
    max-width: 1200px;
    margin: 0 auto;
    display: flex;
    justify-content: space-between;
    align-items: flex-start;
    gap: 16px;
}
.header-text h1 {
    margin: 0 0 8px 0;
    font-size: 1.5rem;
}
.header-meta {
    color: var(--text-secondary);
    font-size: 0.875rem;
    margin: 0;
}
.header-meta a { word-break: break-all; }
.separator { margin: 0 8px; }

/* ===== Theme Toggle ===== */
.theme-toggle {
    background: var(--bg-primary);
    border: 1px solid var(--border-color);
    border-radius: var(--radius);
    padding: 8px 12px;
    cursor: pointer;
    color: var(--text-primary);
    font-size: 1.1rem;
    flex-shrink: 0;
    transition: background 0.2s, border-color 0.2s;
}
.theme-toggle:hover { border-color: var(--accent); }
.theme-toggle:focus { outline: 2px solid var(--accent); outline-offset: 2px; }

.theme-toggle .icon-sun,
.theme-toggle .icon-moon { display: none; }
[data-theme="dark"] .theme-toggle .icon-sun { display: inline; }
[data-theme="light"] .theme-toggle .icon-moon { display: inline; }
:root:not([data-theme]) .theme-toggle .icon-moon { display: inline; }

@media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) .theme-toggle .icon-sun { display: inline; }
    :root:not([data-theme="light"]) .theme-toggle .icon-moon { display: none; }
}

/* ===== Navigation ===== */
.report-nav {
    position: sticky;
    top: 0;
    z-index: 100;
    background: var(--bg-primary);
    border-bottom: 1px solid var(--border-color);
    padding: 0 32px;
    display: flex;
    gap: 4px;
    overflow-x: auto;
    max-width: 100%;
}
.report-nav a {
    padding: 12px 16px;
    white-space: nowrap;
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--text-secondary);
    border-bottom: 2px solid transparent;
    transition: color 0.2s, border-color 0.2s;
}
.report-nav a:hover {
    color: var(--text-primary);
    text-decoration: none;
    border-bottom-color: var(--border-color);
}

/* ===== Main ===== */
main {
    max-width: 1200px;
    margin: 0 auto;
    padding: 32px;
}
section { margin-bottom: 48px; }
h2 {
    font-size: 1.25rem;
    margin: 0 0 16px 0;
    padding-bottom: 8px;
    border-bottom: 1px solid var(--border-color);
}

.section-desc {
    color: var(--text-secondary);
    margin: -8px 0 16px 0;
    font-size: 0.875rem;
}
.empty-state {
    color: var(--text-secondary);
    font-style: italic;
    padding: 24px;
    text-align: center;
    background: var(--bg-secondary);
    border-radius: var(--radius);
}

/* ===== Engine Cards ===== */
.engine-cards {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(220px, 1fr));
    gap: 16px;
    margin-bottom: 24px;
}
.engine-card {
    background: var(--bg-secondary);
    border: 1px solid var(--border-color);
    border-radius: var(--radius);
    padding: 16px;
    box-shadow: var(--shadow);
}
.engine-card-error {
    border-color: var(--error);
    background: var(--error-bg);
}
.card-header {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    margin-bottom: 12px;
}
.engine-name { font-weight: 600; font-size: 1rem; }
.engine-abbr { color: var(--text-secondary); font-size: 0.75rem; }
.engine-version { color: var(--text-secondary); font-size: 0.75rem; }
.violation-count {
    font-size: 2rem;
    font-weight: 700;
    line-height: 1;
}
.violation-label {
    color: var(--text-secondary);
    font-size: 0.875rem;
    margin-bottom: 8px;
}
.card-stats {
    display: flex;
    gap: 12px;
    font-size: 0.8rem;
    color: var(--text-secondary);
}
.stat-pass { color: var(--success); }
.error-msg { color: var(--error); font-size: 0.875rem; }

/* ===== Impact Badges ===== */
.impact-breakdown {
    display: flex;
    flex-wrap: wrap;
    gap: 6px;
    margin-top: 8px;
}
.impact-badge {
    display: inline-block;
    padding: 2px 8px;
    border-radius: 12px;
    font-size: 0.75rem;
    font-weight: 500;
}
.impact-critical { background: var(--error-bg); color: var(--error); }
.impact-serious { background: var(--warning-bg); color: var(--warning); }
.impact-moderate { background: #ddf4ff; color: #0550ae; }
.impact-minor { background: var(--bg-secondary); color: var(--text-secondary); border: 1px solid var(--border-color); }
.impact-violation { background: var(--error-bg); color: var(--error); }
.impact-error { background: var(--error-bg); color: var(--error); }
.impact-unknown { background: var(--bg-secondary); color: var(--text-secondary); }

[data-theme="dark"] .impact-moderate,
:root:not([data-theme="light"]) .impact-moderate {
    background: #0c2d6b; color: #79c0ff;
}
@media (prefers-color-scheme: dark) {
    :root:not([data-theme="light"]) .impact-moderate {
        background: #0c2d6b; color: #79c0ff;
    }
}

/* ===== Agreement Gauge ===== */
.agreement-section {
    background: var(--bg-secondary);
    border: 1px solid var(--border-color);
    border-radius: var(--radius);
    padding: 16px 20px;
}
.agreement-section h3 {
    margin: 0 0 8px 0;
    font-size: 0.95rem;
}
.agreement-gauge {
    height: 24px;
    background: var(--bg-code);
    border-radius: 12px;
    position: relative;
    overflow: hidden;
    margin-bottom: 8px;
}
.gauge-bar {
    height: 100%;
    border-radius: 12px;
    transition: width 0.5s ease;
}
.gauge-high .gauge-bar { background: var(--success); }
.gauge-medium .gauge-bar { background: var(--warning); }
.gauge-low .gauge-bar { background: var(--error); }
.gauge-label {
    position: absolute;
    right: 8px;
    top: 50%;
    transform: translateY(-50%);
    font-size: 0.8rem;
    font-weight: 600;
}
.agreement-detail {
    color: var(--text-secondary);
    font-size: 0.8rem;
    margin: 0;
}

/* ===== Data Tables ===== */
.table-scroll {
    overflow-x: auto;
    -webkit-overflow-scrolling: touch;
}
.data-table {
    width: 100%;
    border-collapse: collapse;
    font-size: 0.875rem;
}
.data-table th,
.data-table td {
    padding: 8px 12px;
    text-align: left;
    border-bottom: 1px solid var(--border-color);
    vertical-align: top;
}
.data-table th {
    background: var(--bg-secondary);
    font-weight: 600;
    white-space: nowrap;
    position: sticky;
    top: 0;
}
.data-table th[data-sortable] {
    cursor: pointer;
    user-select: none;
}
.data-table th[data-sortable]:hover {
    background: var(--bg-code);
}
.data-table th[data-sortable]::after {
    content: " \\2195";
    opacity: 0.3;
}
.data-table th.sort-asc::after { content: " \\2191"; opacity: 1; }
.data-table th.sort-desc::after { content: " \\2193"; opacity: 1; }
.data-table tbody tr:hover {
    background: var(--bg-secondary);
}
.sc-number { font-weight: 600; white-space: nowrap; }
.sc-level { white-space: nowrap; }
.count-cell { text-align: right; }

/* Status cells */
.status-pass { color: var(--success); }
.status-violation { color: var(--error); font-weight: 600; }
.status-incomplete { color: var(--warning); }
.text-fail { color: var(--error); }
.text-pass { color: var(--success); }

/* Row filtering */
.row-pass.hidden-pass { display: none; }

/* Table controls */
.table-controls {
    margin-bottom: 12px;
}
.filter-toggle {
    display: inline-flex;
    align-items: center;
    gap: 6px;
    font-size: 0.875rem;
    color: var(--text-secondary);
    cursor: pointer;
}
.filter-toggle input { cursor: pointer; }

/* ===== Tabs ===== */
.tabs-container { margin-top: 8px; }
.tabs {
    display: flex;
    gap: 0;
    border-bottom: 1px solid var(--border-color);
    overflow-x: auto;
}
.tab {
    padding: 10px 20px;
    border: none;
    background: none;
    cursor: pointer;
    font-size: 0.875rem;
    font-weight: 500;
    color: var(--text-secondary);
    border-bottom: 2px solid transparent;
    white-space: nowrap;
    font-family: var(--font-sans);
    transition: color 0.15s, border-color 0.15s;
}
.tab:hover { color: var(--text-primary); }
.tab[aria-selected="true"],
.tab.active {
    color: var(--accent);
    border-bottom-color: var(--accent);
}
.tab:focus {
    outline: 2px solid var(--accent);
    outline-offset: -2px;
}
.tab-panel {
    padding: 16px 0;
}

/* ===== Node Details ===== */
.node-details {
    margin-top: 8px;
}
.node-details summary {
    cursor: pointer;
    color: var(--accent);
    font-size: 0.8rem;
}
.node-details summary:hover { text-decoration: underline; }
.node-list {
    list-style: none;
    padding: 0;
    margin: 8px 0 0 0;
}
.node-item {
    padding: 8px;
    margin-bottom: 4px;
    background: var(--bg-secondary);
    border-radius: var(--radius-sm);
    border-left: 3px solid var(--border-color);
}
.node-selector { margin-bottom: 4px; }
.node-selector code {
    font-size: 0.8rem;
    word-break: break-all;
}
.node-html pre {
    margin: 4px 0;
    background: var(--bg-code);
    border-radius: var(--radius-sm);
}
.node-html code { font-size: 0.8rem; }
.node-failure {
    color: var(--text-secondary);
    font-size: 0.8rem;
    margin-top: 4px;
}

/* ===== Rule table ===== */
.rule-id { white-space: nowrap; }
.rule-table td:last-child { max-width: 500px; }

/* ===== Recommendations ===== */
.rec-group {
    margin-bottom: 8px;
    border: 1px solid var(--border-color);
    border-radius: var(--radius);
}
.rec-group summary {
    cursor: pointer;
    padding: 10px 16px;
    font-weight: 500;
    background: var(--bg-secondary);
    border-radius: var(--radius);
}
.rec-group[open] summary {
    border-bottom: 1px solid var(--border-color);
    border-radius: var(--radius) var(--radius) 0 0;
}
.rec-table { font-size: 0.8rem; }
.rec-table td { max-width: 400px; word-break: break-word; }

/* ===== Footer ===== */
.report-footer {
    text-align: center;
    padding: 24px 32px;
    color: var(--text-secondary);
    font-size: 0.8rem;
    border-top: 1px solid var(--border-color);
}

/* ===== Print ===== */
@media print {
    .report-nav,
    .theme-toggle,
    .skip-link,
    .filter-toggle { display: none; }
    body { font-size: 10pt; }
    .engine-cards { grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); }
    .tab-panel { display: block !important; }
    .tab-panel[hidden] { display: block !important; }
    .tabs { display: none; }
    details { break-inside: avoid; }
    details[open] summary ~ * { break-inside: avoid; }
    .row-pass.hidden-pass { display: table-row !important; }
}

/* ===== Responsive ===== */
@media (max-width: 768px) {
    .report-header { padding: 16px; }
    .header-content { flex-direction: column; }
    main { padding: 16px; }
    .engine-cards { grid-template-columns: 1fr; }
    .report-nav { padding: 0 16px; }
}
"""


def _get_report_js() -> str:
    """Return the complete JavaScript for the report."""
    return """
// Theme toggle
(function() {
    var toggle = document.getElementById('theme-toggle');
    var html = document.documentElement;

    function getPreferredTheme() {
        var stored = localStorage.getItem('inspekt-theme');
        if (stored) return stored;
        return window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light';
    }

    function setTheme(theme) {
        html.setAttribute('data-theme', theme);
        localStorage.setItem('inspekt-theme', theme);
    }

    setTheme(getPreferredTheme());

    toggle.addEventListener('click', function() {
        var current = html.getAttribute('data-theme') || getPreferredTheme();
        setTheme(current === 'dark' ? 'light' : 'dark');
    });

    window.matchMedia('(prefers-color-scheme: dark)').addEventListener('change', function(e) {
        if (!localStorage.getItem('inspekt-theme')) {
            setTheme(e.matches ? 'dark' : 'light');
        }
    });
})();

// Accessible tab navigation
(function() {
    var tabLists = document.querySelectorAll('[role="tablist"]');
    tabLists.forEach(function(tabList) {
        var tabs = tabList.querySelectorAll('[role="tab"]');
        var panels = [];

        tabs.forEach(function(tab) {
            var panelId = tab.getAttribute('aria-controls');
            var panel = document.getElementById(panelId);
            if (panel) panels.push(panel);
        });

        function selectTab(tab) {
            tabs.forEach(function(t) {
                t.setAttribute('aria-selected', 'false');
                t.setAttribute('tabindex', '-1');
                t.classList.remove('active');
            });
            panels.forEach(function(p) { p.hidden = true; });

            tab.setAttribute('aria-selected', 'true');
            tab.setAttribute('tabindex', '0');
            tab.classList.add('active');
            tab.focus();

            var panelId = tab.getAttribute('aria-controls');
            var panel = document.getElementById(panelId);
            if (panel) panel.hidden = false;
        }

        tabs.forEach(function(tab) {
            tab.addEventListener('click', function() { selectTab(tab); });

            tab.addEventListener('keydown', function(e) {
                var index = Array.from(tabs).indexOf(tab);
                var newIndex;

                if (e.key === 'ArrowRight' || e.key === 'ArrowDown') {
                    newIndex = (index + 1) % tabs.length;
                    e.preventDefault();
                } else if (e.key === 'ArrowLeft' || e.key === 'ArrowUp') {
                    newIndex = (index - 1 + tabs.length) % tabs.length;
                    e.preventDefault();
                } else if (e.key === 'Home') {
                    newIndex = 0;
                    e.preventDefault();
                } else if (e.key === 'End') {
                    newIndex = tabs.length - 1;
                    e.preventDefault();
                }

                if (newIndex !== undefined) {
                    selectTab(tabs[newIndex]);
                }
            });
        });
    });
})();

// Table sorting
(function() {
    var tables = document.querySelectorAll('.sortable-table');
    tables.forEach(function(table) {
        var headers = table.querySelectorAll('th[data-sortable]');
        headers.forEach(function(header, colIndex) {
            header.addEventListener('click', function() {
                var tbody = table.querySelector('tbody');
                var rows = Array.from(tbody.querySelectorAll('tr'));
                var isAsc = header.classList.contains('sort-asc');

                // Remove sort classes from all headers
                headers.forEach(function(h) {
                    h.classList.remove('sort-asc', 'sort-desc');
                });

                // Toggle direction
                header.classList.add(isAsc ? 'sort-desc' : 'sort-asc');
                var direction = isAsc ? -1 : 1;

                rows.sort(function(a, b) {
                    var aCell = a.cells[colIndex];
                    var bCell = b.cells[colIndex];
                    var aVal = aCell.getAttribute('data-sort-value') || aCell.textContent.trim();
                    var bVal = bCell.getAttribute('data-sort-value') || bCell.textContent.trim();

                    // Try numeric sort
                    var aNum = parseFloat(aVal);
                    var bNum = parseFloat(bVal);
                    if (!isNaN(aNum) && !isNaN(bNum)) {
                        return (aNum - bNum) * direction;
                    }
                    return aVal.localeCompare(bVal) * direction;
                });

                rows.forEach(function(row) { tbody.appendChild(row); });
            });
        });
    });
})();

// Filter passes toggle
(function() {
    var checkbox = document.getElementById('filter-passes');
    if (!checkbox) return;

    function applyFilter() {
        var rows = document.querySelectorAll('.row-pass');
        rows.forEach(function(row) {
            if (checkbox.checked) {
                row.classList.add('hidden-pass');
            } else {
                row.classList.remove('hidden-pass');
            }
        });
    }

    checkbox.addEventListener('change', applyFilter);
    applyFilter(); // Apply initial state
})();

// Smooth scroll for nav links
(function() {
    var navLinks = document.querySelectorAll('.report-nav a');
    navLinks.forEach(function(link) {
        link.addEventListener('click', function(e) {
            var targetId = link.getAttribute('href').substring(1);
            var target = document.getElementById(targetId);
            if (target) {
                e.preventDefault();
                target.scrollIntoView({ behavior: 'smooth', block: 'start' });
                // Update URL hash without jumping
                history.pushState(null, null, '#' + targetId);
            }
        });
    });
})();
"""
