"""
Test that all CLI commands have corresponding CommandDefinitions.

This test ensures the CommandRegistry is the single source of truth
by failing CI if any CLI command lacks a definition.

Run with: pytest tests/unit/test_command_registry_sync.py -v
"""

import pytest


# Commands intentionally excluded from validation
# These are hidden aliases or internal commands that don't need registry entries
EXCLUDED_COMMANDS = {
    # Navigation aliases (hidden, point to same functionality)
    "previous",  # alias for back
    "next",  # alias for forward
    "refresh",  # alias for reload
    "pgup",  # alias for pageup
    "pgdown",  # alias for pagedown
    "home",  # alias for top
    "end",  # alias for bottom
    # Interaction aliases
    "doubleclick",  # alias for double-click
    "rightclick",  # alias for right-click
    # Execution aliases
    "eval",  # alias for exec
    "exec",  # alias for js
    # Deprecated commands that redirect
    "go",  # deprecated, redirects to open
    # Shell completion (auto-generated by Click)
    "completion",
    "completion.bash",
    "completion.fish",
    "completion.install",
    "completion.status",
    "completion.uninstall",
    "completion.zsh",
    # Setup/config commands (internal)
    "config",
    "setup",
}


class TestCommandRegistrySync:
    """Test suite for CLI/Registry synchronization."""

    def test_all_cli_commands_have_definitions(self):
        """
        Every non-excluded CLI command must have a CommandDefinition.

        This is the core validation test that ensures the registry
        is complete and the dashboard will show all commands.
        """
        from inspekt.core.cli_introspection import find_missing_definitions

        missing = find_missing_definitions(excluded=EXCLUDED_COMMANDS)

        if missing:
            # Format a helpful error message
            msg = (
                f"CLI commands missing CommandDefinitions ({len(missing)}):\n"
                f"{chr(10).join(f'  - {name}' for name in missing)}\n\n"
                f"To fix: Add CommandDefinition for each command in "
                f"inspekt/core/commands/"
            )
            pytest.fail(msg)

    def test_no_duplicate_cli_names(self):
        """No two commands should have the same CLI name."""
        from inspekt.core.commands import register_all_commands
        from inspekt.core.registry import get_registry

        register_all_commands()
        registry = get_registry()

        names: dict[str, str] = {}
        conflicts = []

        for cmd in registry.get_all():
            cli_name = cmd.get_cli_name()

            # Check main CLI name
            if cli_name in names:
                conflicts.append(
                    f"{cli_name}: {names[cli_name]} vs {cmd.id}"
                )
            else:
                names[cli_name] = cmd.id

            # Check aliases
            for alias in cmd.cli_aliases:
                if alias in names:
                    conflicts.append(
                        f"{alias}: {names[alias]} vs {cmd.id}"
                    )
                else:
                    names[alias] = cmd.id

        if conflicts:
            pytest.fail(f"CLI name conflicts:\n" + "\n".join(conflicts))

    def test_command_ids_are_unique(self):
        """All command IDs must be unique."""
        from inspekt.core.commands import register_all_commands
        from inspekt.core.registry import get_registry

        register_all_commands()
        registry = get_registry()

        ids: dict[str, int] = {}
        for cmd in registry.get_all():
            ids[cmd.id] = ids.get(cmd.id, 0) + 1

        duplicates = [id for id, count in ids.items() if count > 1]

        if duplicates:
            pytest.fail(
                f"Duplicate command IDs: {', '.join(duplicates)}"
            )

    def test_categories_are_valid(self):
        """All commands must have valid Category values."""
        from inspekt.core.commands import register_all_commands
        from inspekt.core.commands.base import Category
        from inspekt.core.registry import get_registry

        register_all_commands()
        registry = get_registry()

        valid_categories = set(Category)

        invalid = []
        for cmd in registry.get_all():
            if cmd.category not in valid_categories:
                invalid.append(f"{cmd.id}: {cmd.category}")

        if invalid:
            pytest.fail(
                f"Commands with invalid categories:\n"
                + "\n".join(invalid)
            )

    def test_registry_loads_without_errors(self):
        """The registry should load all commands without import errors."""
        from inspekt.core.commands import register_all_commands
        from inspekt.core.registry import get_registry

        # This will raise if there are import errors
        register_all_commands()
        registry = get_registry()

        # Should have a reasonable number of commands
        commands = registry.get_all()
        assert len(commands) > 30, (
            f"Expected at least 30 commands, got {len(commands)}. "
            f"Some command modules may have failed to load."
        )

    def test_grouped_by_category_works(self):
        """The get_grouped_by_category method should work correctly."""
        from inspekt.core.commands import register_all_commands
        from inspekt.core.registry import get_registry

        register_all_commands()
        registry = get_registry()

        grouped = registry.get_grouped_by_category()

        # Should have multiple categories
        assert len(grouped) > 5, (
            f"Expected at least 5 categories, got {len(grouped)}"
        )

        # Each category should have commands
        for category, commands in grouped.items():
            assert len(commands) > 0, (
                f"Category {category} has no commands"
            )
