"""Autostart management for Inspekt (macOS LaunchAgent).

Provides commands to enable/disable automatic startup of the bridge
and API servers at login using a macOS LaunchAgent.
"""

import platform
import stat
import subprocess
import sys
from pathlib import Path

import click

from inspekt.app.cli.icons import get_indicator, get_status_icon
from inspekt.app.cli.table import Table, format_status_icon, print_hint

# Constants
LABEL = "com.inspekt.servers"
INSPEKT_DIR = Path.home() / ".inspekt"
LOGS_DIR = INSPEKT_DIR / "logs"
WRAPPER_PATH = INSPEKT_DIR / "autostart.sh"
PLIST_PATH = Path.home() / "Library" / "LaunchAgents" / f"{LABEL}.plist"


def _resolve_python() -> str:
    """Resolve the real Python executable path (not a pyenv shim).

    sys.executable already points to the real binary when running
    inside an activated environment, even through a pyenv shim.
    """
    return sys.executable


def _verify_python(python_path: str) -> bool:
    """Verify the resolved Python can import inspekt."""
    result = subprocess.run(
        [python_path, "-c", "import inspekt; print(inspekt.__version__)"],
        capture_output=True,
        text=True,
    )
    return result.returncode == 0


def _build_wrapper_script(python_path: str) -> str:
    """Generate the autostart wrapper shell script."""
    return f"""\
#!/bin/bash
# Inspekt autostart wrapper — generated by `inspekt autostart enable`
# Do not edit manually; re-run `inspekt autostart enable` to regenerate.

PYTHON="{python_path}"
PIDDIR="{INSPEKT_DIR}"

cleanup() {{
    kill "$BRIDGE_PID" "$API_PID" 2>/dev/null
    rm -f "$PIDDIR/bridge.pid" "$PIDDIR/api.pid"
    exit 0
}}
trap cleanup SIGTERM SIGINT

# --- Start bridge server ---
"$PYTHON" -m inspekt.bridge_ws &
BRIDGE_PID=$!
echo "$BRIDGE_PID" > "$PIDDIR/bridge.pid"

# Wait for bridge to become ready (max 10 seconds)
for i in $(seq 1 20); do
    if curl -s -o /dev/null http://127.0.0.1:8765/status 2>/dev/null; then
        break
    fi
    sleep 0.5
done

# --- Start API server ---
"$PYTHON" -m uvicorn inspekt.app.api.server:app --host 127.0.0.1 --port 8000 &
API_PID=$!
echo "$API_PID" > "$PIDDIR/api.pid"

# Keep wrapper alive while children run
wait
"""


def _build_plist(python_path: str) -> str:
    """Generate the LaunchAgent plist XML."""
    python_bin_dir = str(Path(python_path).parent)
    return f"""\
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{LABEL}</string>

    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{WRAPPER_PATH}</string>
    </array>

    <key>RunAtLoad</key>
    <true/>

    <key>KeepAlive</key>
    <false/>

    <key>EnvironmentVariables</key>
    <dict>
        <key>PATH</key>
        <string>{python_bin_dir}:/usr/local/bin:/usr/bin:/bin</string>
        <key>HOME</key>
        <string>{Path.home()}</string>
        <key>INSPEKT_AUTOSTART</key>
        <string>1</string>
    </dict>

    <key>StandardOutPath</key>
    <string>{LOGS_DIR / "launchd.log"}</string>
    <key>StandardErrorPath</key>
    <string>{LOGS_DIR / "launchd.error.log"}</string>
</dict>
</plist>
"""


def _is_agent_loaded() -> bool:
    """Check whether the LaunchAgent is currently loaded."""
    result = subprocess.run(
        ["launchctl", "list", LABEL],
        capture_output=True,
    )
    return result.returncode == 0


def _read_embedded_python() -> str | None:
    """Read the Python path embedded in the existing wrapper script."""
    if not WRAPPER_PATH.exists():
        return None
    try:
        for line in WRAPPER_PATH.read_text().splitlines():
            if line.startswith('PYTHON="'):
                return line.split('"')[1]
    except OSError:
        pass
    return None


# ============================================================================
# CLI Commands
# ============================================================================

@click.group()
def autostart():
    """Manage automatic startup at login (macOS).

    Uses a macOS LaunchAgent to start the bridge and API servers
    automatically when you log in, so you don't have to run
    `inspekt start` manually.

    \b
    Examples:
        inspekt autostart enable    # Install and activate
        inspekt autostart disable   # Remove LaunchAgent
        inspekt autostart status    # Show current state
    """
    pass


@autostart.command()
def enable():
    """Install and activate the LaunchAgent.

    Creates a wrapper script and LaunchAgent plist, then loads
    the agent so servers start automatically at login.

    \b
    What this does:
        1. Resolves the real Python path (not pyenv shim)
        2. Writes a wrapper script to ~/.inspekt/autostart.sh
        3. Writes a plist to ~/Library/LaunchAgents/
        4. Loads the agent via launchctl
    """
    # Platform check
    if platform.system() != "Darwin":
        click.echo(
            click.style("Error: ", fg="red")
            + "Autostart is only supported on macOS (LaunchAgent).",
            err=True,
        )
        raise SystemExit(1)

    # Resolve Python
    python_path = _resolve_python()
    click.echo(f"  Python: {click.style(python_path, fg='cyan')}")

    if not _verify_python(python_path):
        click.echo(
            click.style("Error: ", fg="red")
            + f"Cannot import inspekt with {python_path}",
            err=True,
        )
        raise SystemExit(1)

    # Create directories
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    PLIST_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Unload existing agent first (ignore errors if not loaded)
    if _is_agent_loaded():
        subprocess.run(
            ["launchctl", "unload", str(PLIST_PATH)],
            capture_output=True,
        )

    # Write wrapper script
    WRAPPER_PATH.write_text(_build_wrapper_script(python_path))
    WRAPPER_PATH.chmod(WRAPPER_PATH.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP)

    # Write plist
    PLIST_PATH.write_text(_build_plist(python_path))

    # Load agent
    result = subprocess.run(
        ["launchctl", "load", str(PLIST_PATH)],
        capture_output=True,
        text=True,
    )

    if result.returncode != 0:
        click.echo(
            click.style("Error: ", fg="red")
            + f"launchctl load failed: {result.stderr.strip()}",
            err=True,
        )
        raise SystemExit(1)

    # Success output
    click.echo()
    table = Table(
        ["Property", "Value"],
        title="Autostart Enabled",
        icon=get_indicator("pass"),
    )
    data = [
        ["Status", f"{format_status_icon('pass')} " + click.style("Enabled", fg="green")],
        ["Python", python_path],
        ["Wrapper", str(WRAPPER_PATH)],
        ["Plist", str(PLIST_PATH)],
        ["Stdout log", str(LOGS_DIR / "launchd.log")],
        ["Stderr log", str(LOGS_DIR / "launchd.error.log")],
    ]
    table.set_data(data)
    table.print_header(skip_column_headers=True)
    for row in data:
        table.print_row(row)
    table.print_footer()

    click.echo()
    print_hint("Servers will now start automatically at login. Check with `inspekt autostart status`.")


@autostart.command()
def disable():
    """Remove the LaunchAgent and wrapper script.

    Unloads the agent and removes the generated files.
    Log files in ~/.inspekt/logs/ are kept for debugging.
    Running servers are not stopped.

    \b
    Examples:
        inspekt autostart disable
    """
    if platform.system() != "Darwin":
        click.echo(
            click.style("Error: ", fg="red")
            + "Autostart is only supported on macOS.",
            err=True,
        )
        raise SystemExit(1)

    anything_removed = False

    # Unload agent
    if _is_agent_loaded():
        result = subprocess.run(
            ["launchctl", "unload", str(PLIST_PATH)],
            capture_output=True,
            text=True,
        )
        if result.returncode == 0:
            click.echo(f"  {get_status_icon('pass')} Agent unloaded")
            anything_removed = True
        else:
            click.echo(f"  {get_status_icon('warning')} Could not unload agent: {result.stderr.strip()}", err=True)

    # Remove plist
    if PLIST_PATH.exists():
        PLIST_PATH.unlink()
        click.echo(f"  {get_status_icon('pass')} Removed {PLIST_PATH}")
        anything_removed = True

    # Remove wrapper script
    if WRAPPER_PATH.exists():
        WRAPPER_PATH.unlink()
        click.echo(f"  {get_status_icon('pass')} Removed {WRAPPER_PATH}")
        anything_removed = True

    # Remove PID files
    for pidfile in ("bridge.pid", "api.pid"):
        p = INSPEKT_DIR / pidfile
        if p.exists():
            p.unlink()

    if anything_removed:
        click.echo(f"\n  {click.style('Autostart disabled.', fg='green')}")
    else:
        click.echo("  Autostart was not enabled.")

    print_hint("Running servers are not stopped. Use `inspekt stop` to stop them.")


@autostart.command()
def status():
    """Show the current autostart status.

    Displays whether the LaunchAgent is installed and loaded,
    the embedded Python path, and log file locations.
    Warns if the Python path has changed since enabling.

    \b
    Examples:
        inspekt autostart status
    """
    if platform.system() != "Darwin":
        click.echo(
            click.style("Error: ", fg="red")
            + "Autostart is only supported on macOS.",
            err=True,
        )
        raise SystemExit(1)

    plist_exists = PLIST_PATH.exists()
    loaded = _is_agent_loaded()
    embedded_python = _read_embedded_python()
    current_python = _resolve_python()

    click.echo()
    table = Table(
        ["Property", "Value"],
        title="Autostart Status",
        icon=get_indicator("info_circle"),
    )

    # Status
    if loaded:
        status_text = f"{format_status_icon('pass')} " + click.style("Enabled & loaded", fg="green")
    elif plist_exists:
        status_text = f"{format_status_icon('warning')} " + click.style("Installed but not loaded", fg="yellow")
    else:
        status_text = f"{format_status_icon('fail')} " + click.style("Not enabled", fg="red")

    data = [
        ["Status", status_text],
        ["Plist", str(PLIST_PATH) if plist_exists else click.style("not found", fg="bright_black")],
        ["Wrapper", str(WRAPPER_PATH) if WRAPPER_PATH.exists() else click.style("not found", fg="bright_black")],
    ]

    # Python path info
    if embedded_python:
        data.append(["Python (embedded)", embedded_python])
        if embedded_python != current_python:
            data.append([
                "",
                click.style(f"⚠ Current Python differs: {current_python}", fg="yellow"),
            ])
    else:
        data.append(["Python (current)", current_python])

    # Log files
    stdout_log = LOGS_DIR / "launchd.log"
    stderr_log = LOGS_DIR / "launchd.error.log"
    if stdout_log.exists():
        data.append(["Stdout log", str(stdout_log)])
    if stderr_log.exists():
        data.append(["Stderr log", str(stderr_log)])

    table.set_data(data)
    table.print_header(skip_column_headers=True)
    for row in data:
        table.print_row(row)
    table.print_footer()

    # Warnings and hints
    if embedded_python and embedded_python != current_python:
        click.echo()
        print_hint("Python path has changed. Re-run `inspekt autostart enable` to update.")

    if not plist_exists:
        click.echo()
        print_hint("Run `inspekt autostart enable` to set up automatic startup at login.")
